
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)

interface _GlobalComponents {
      'VarActionSheet': typeof import("../../node_modules/@varlet/ui/es/action-sheet/index")['_ActionSheetComponent']
    'VarActionSheetStyle': typeof import("../../node_modules/@varlet/ui/es/action-sheet/style/index")['_ActionSheetStyleComponent']
    'VarAlert': typeof import("../../node_modules/@varlet/ui/es/alert/index")['_AlertComponent']
    'VarAlertStyle': typeof import("../../node_modules/@varlet/ui/es/alert/style/index")['_AlertStyleComponent']
    'VarAppBar': typeof import("../../node_modules/@varlet/ui/es/app-bar/index")['_AppBarComponent']
    'VarAppBarStyle': typeof import("../../node_modules/@varlet/ui/es/app-bar/style/index")['_AppBarStyleComponent']
    'VarAutoComplete': typeof import("../../node_modules/@varlet/ui/es/auto-complete/index")['_AutoCompleteComponent']
    'VarAutoCompleteStyle': typeof import("../../node_modules/@varlet/ui/es/auto-complete/style/index")['_AutoCompleteStyleComponent']
    'VarAvatarGroup': typeof import("../../node_modules/@varlet/ui/es/avatar-group/index")['_AvatarGroupComponent']
    'VarAvatarGroupStyle': typeof import("../../node_modules/@varlet/ui/es/avatar-group/style/index")['_AvatarGroupStyleComponent']
    'VarAvatar': typeof import("../../node_modules/@varlet/ui/es/avatar/index")['_AvatarComponent']
    'VarAvatarStyle': typeof import("../../node_modules/@varlet/ui/es/avatar/style/index")['_AvatarStyleComponent']
    'VarBackTop': typeof import("../../node_modules/@varlet/ui/es/back-top/index")['_BackTopComponent']
    'VarBackTopStyle': typeof import("../../node_modules/@varlet/ui/es/back-top/style/index")['_BackTopStyleComponent']
    'VarBadge': typeof import("../../node_modules/@varlet/ui/es/badge/index")['_BadgeComponent']
    'VarBadgeStyle': typeof import("../../node_modules/@varlet/ui/es/badge/style/index")['_BadgeStyleComponent']
    'VarBottomNavigationItem': typeof import("../../node_modules/@varlet/ui/es/bottom-navigation-item/index")['_BottomNavigationItemComponent']
    'VarBottomNavigationItemStyle': typeof import("../../node_modules/@varlet/ui/es/bottom-navigation-item/style/index")['_BottomNavigationItemStyleComponent']
    'VarBottomNavigation': typeof import("../../node_modules/@varlet/ui/es/bottom-navigation/index")['_BottomNavigationComponent']
    'VarBottomNavigationStyle': typeof import("../../node_modules/@varlet/ui/es/bottom-navigation/style/index")['_BottomNavigationStyleComponent']
    'VarBreadcrumb': typeof import("../../node_modules/@varlet/ui/es/breadcrumb/index")['_BreadcrumbComponent']
    'VarBreadcrumbStyle': typeof import("../../node_modules/@varlet/ui/es/breadcrumb/style/index")['_BreadcrumbStyleComponent']
    'VarBreadcrumbs': typeof import("../../node_modules/@varlet/ui/es/breadcrumbs/index")['_BreadcrumbsComponent']
    'VarBreadcrumbsStyle': typeof import("../../node_modules/@varlet/ui/es/breadcrumbs/style/index")['_BreadcrumbsStyleComponent']
    'VarButtonGroup': typeof import("../../node_modules/@varlet/ui/es/button-group/index")['_ButtonGroupComponent']
    'VarButtonGroupStyle': typeof import("../../node_modules/@varlet/ui/es/button-group/style/index")['_ButtonGroupStyleComponent']
    'VarButton': typeof import("../../node_modules/@varlet/ui/es/button/index")['_ButtonComponent']
    'VarButtonStyle': typeof import("../../node_modules/@varlet/ui/es/button/style/index")['_ButtonStyleComponent']
    'VarCard': typeof import("../../node_modules/@varlet/ui/es/card/index")['_CardComponent']
    'VarCardStyle': typeof import("../../node_modules/@varlet/ui/es/card/style/index")['_CardStyleComponent']
    'VarCell': typeof import("../../node_modules/@varlet/ui/es/cell/index")['_CellComponent']
    'VarCellStyle': typeof import("../../node_modules/@varlet/ui/es/cell/style/index")['_CellStyleComponent']
    'VarCheckboxGroup': typeof import("../../node_modules/@varlet/ui/es/checkbox-group/index")['_CheckboxGroupComponent']
    'VarCheckboxGroupStyle': typeof import("../../node_modules/@varlet/ui/es/checkbox-group/style/index")['_CheckboxGroupStyleComponent']
    'VarCheckbox': typeof import("../../node_modules/@varlet/ui/es/checkbox/index")['_CheckboxComponent']
    'VarCheckboxStyle': typeof import("../../node_modules/@varlet/ui/es/checkbox/style/index")['_CheckboxStyleComponent']
    'VarChip': typeof import("../../node_modules/@varlet/ui/es/chip/index")['_ChipComponent']
    'VarChipStyle': typeof import("../../node_modules/@varlet/ui/es/chip/style/index")['_ChipStyleComponent']
    'VarCode': typeof import("../../node_modules/@varlet/ui/es/code/index")['_CodeComponent']
    'VarCodeStyle': typeof import("../../node_modules/@varlet/ui/es/code/style/index")['_CodeStyleComponent']
    'VarCol': typeof import("../../node_modules/@varlet/ui/es/col/index")['_ColComponent']
    'VarColStyle': typeof import("../../node_modules/@varlet/ui/es/col/style/index")['_ColStyleComponent']
    'VarCollapseItem': typeof import("../../node_modules/@varlet/ui/es/collapse-item/index")['_CollapseItemComponent']
    'VarCollapseItemStyle': typeof import("../../node_modules/@varlet/ui/es/collapse-item/style/index")['_CollapseItemStyleComponent']
    'VarCollapseTransition': typeof import("../../node_modules/@varlet/ui/es/collapse-transition/index")['_CollapseTransitionComponent']
    'VarCollapseTransitionStyle': typeof import("../../node_modules/@varlet/ui/es/collapse-transition/style/index")['_CollapseTransitionStyleComponent']
    'VarCollapse': typeof import("../../node_modules/@varlet/ui/es/collapse/index")['_CollapseComponent']
    'VarCollapseStyle': typeof import("../../node_modules/@varlet/ui/es/collapse/style/index")['_CollapseStyleComponent']
    'VarContext': typeof import("../../node_modules/@varlet/ui/es/context/index")['_ContextComponent']
    'VarContextStyle': typeof import("../../node_modules/@varlet/ui/es/context/style/index")['_ContextStyleComponent']
    'VarCountTo': typeof import("../../node_modules/@varlet/ui/es/count-to/index")['_CountToComponent']
    'VarCountToStyle': typeof import("../../node_modules/@varlet/ui/es/count-to/style/index")['_CountToStyleComponent']
    'VarCountdown': typeof import("../../node_modules/@varlet/ui/es/countdown/index")['_CountdownComponent']
    'VarCountdownStyle': typeof import("../../node_modules/@varlet/ui/es/countdown/style/index")['_CountdownStyleComponent']
    'VarCounter': typeof import("../../node_modules/@varlet/ui/es/counter/index")['_CounterComponent']
    'VarCounterStyle': typeof import("../../node_modules/@varlet/ui/es/counter/style/index")['_CounterStyleComponent']
    'VarDatePicker': typeof import("../../node_modules/@varlet/ui/es/date-picker/index")['_DatePickerComponent']
    'VarDatePickerStyle': typeof import("../../node_modules/@varlet/ui/es/date-picker/style/index")['_DatePickerStyleComponent']
    'VarDialog': typeof import("../../node_modules/@varlet/ui/es/dialog/index")['_DialogComponent']
    'VarDialogStyle': typeof import("../../node_modules/@varlet/ui/es/dialog/style/index")['_DialogStyleComponent']
    'VarDivider': typeof import("../../node_modules/@varlet/ui/es/divider/index")['_DividerComponent']
    'VarDividerStyle': typeof import("../../node_modules/@varlet/ui/es/divider/style/index")['_DividerStyleComponent']
    'VarDrag': typeof import("../../node_modules/@varlet/ui/es/drag/index")['_DragComponent']
    'VarDragStyle': typeof import("../../node_modules/@varlet/ui/es/drag/style/index")['_DragStyleComponent']
    'VarEllipsis': typeof import("../../node_modules/@varlet/ui/es/ellipsis/index")['_EllipsisComponent']
    'VarEllipsisStyle': typeof import("../../node_modules/@varlet/ui/es/ellipsis/style/index")['_EllipsisStyleComponent']
    'VarFab': typeof import("../../node_modules/@varlet/ui/es/fab/index")['_FabComponent']
    'VarFabStyle': typeof import("../../node_modules/@varlet/ui/es/fab/style/index")['_FabStyleComponent']
    'VarFieldDecorator': typeof import("../../node_modules/@varlet/ui/es/field-decorator/index")['_FieldDecoratorComponent']
    'VarFieldDecoratorStyle': typeof import("../../node_modules/@varlet/ui/es/field-decorator/style/index")['_FieldDecoratorStyleComponent']
    'VarFloatingPanel': typeof import("../../node_modules/@varlet/ui/es/floating-panel/index")['_FloatingPanelComponent']
    'VarFloatingPanelStyle': typeof import("../../node_modules/@varlet/ui/es/floating-panel/style/index")['_FloatingPanelStyleComponent']
    'VarFormDetails': typeof import("../../node_modules/@varlet/ui/es/form-details/index")['_FormDetailsComponent']
    'VarFormDetailsStyle': typeof import("../../node_modules/@varlet/ui/es/form-details/style/index")['_FormDetailsStyleComponent']
    'VarForm': typeof import("../../node_modules/@varlet/ui/es/form/index")['_FormComponent']
    'VarFormStyle': typeof import("../../node_modules/@varlet/ui/es/form/style/index")['_FormStyleComponent']
    'VarHighlighterProvider': typeof import("../../node_modules/@varlet/ui/es/highlighter-provider/index")['_HighlighterProviderComponent']
    'VarHighlighterProviderStyle': typeof import("../../node_modules/@varlet/ui/es/highlighter-provider/style/index")['_HighlighterProviderStyleComponent']
    'VarHoverOverlay': typeof import("../../node_modules/@varlet/ui/es/hover-overlay/index")['_HoverOverlayComponent']
    'VarHoverOverlayStyle': typeof import("../../node_modules/@varlet/ui/es/hover-overlay/style/index")['_HoverOverlayStyleComponent']
    'VarHover': typeof import("../../node_modules/@varlet/ui/es/hover/index")['_HoverComponent']
    'VarHoverStyle': typeof import("../../node_modules/@varlet/ui/es/hover/style/index")['_HoverStyleComponent']
    'VarIcon': typeof import("../../node_modules/@varlet/ui/es/icon/index")['_IconComponent']
    'VarIconStyle': typeof import("../../node_modules/@varlet/ui/es/icon/style/index")['_IconStyleComponent']
    'VarImagePreview': typeof import("../../node_modules/@varlet/ui/es/image-preview/index")['_ImagePreviewComponent']
    'VarImagePreviewStyle': typeof import("../../node_modules/@varlet/ui/es/image-preview/style/index")['_ImagePreviewStyleComponent']
    'VarImage': typeof import("../../node_modules/@varlet/ui/es/image/index")['_ImageComponent']
    'VarImageStyle': typeof import("../../node_modules/@varlet/ui/es/image/style/index")['_ImageStyleComponent']
    'VarIndexAnchor': typeof import("../../node_modules/@varlet/ui/es/index-anchor/index")['_IndexAnchorComponent']
    'VarIndexAnchorStyle': typeof import("../../node_modules/@varlet/ui/es/index-anchor/style/index")['_IndexAnchorStyleComponent']
    'VarIndexBar': typeof import("../../node_modules/@varlet/ui/es/index-bar/index")['_IndexBarComponent']
    'VarIndexBarStyle': typeof import("../../node_modules/@varlet/ui/es/index-bar/style/index")['_IndexBarStyleComponent']
    'VarIndexBundle': typeof import("../../node_modules/@varlet/ui/es/index.bundle")['_IndexBundleComponent']
    'Var': typeof import("../../node_modules/@varlet/ui/es/index")['_Component']
    'VarInput': typeof import("../../node_modules/@varlet/ui/es/input/index")['_InputComponent']
    'VarInputStyle': typeof import("../../node_modules/@varlet/ui/es/input/style/index")['_InputStyleComponent']
    'VarLazy': typeof import("../../node_modules/@varlet/ui/es/lazy/index")['_LazyComponent']
    'VarLazyStyle': typeof import("../../node_modules/@varlet/ui/es/lazy/style/index")['_LazyStyleComponent']
    'VarLink': typeof import("../../node_modules/@varlet/ui/es/link/index")['_LinkComponent']
    'VarLinkStyle': typeof import("../../node_modules/@varlet/ui/es/link/style/index")['_LinkStyleComponent']
    'VarList': typeof import("../../node_modules/@varlet/ui/es/list/index")['_ListComponent']
    'VarListStyle': typeof import("../../node_modules/@varlet/ui/es/list/style/index")['_ListStyleComponent']
    'VarLoadingBar': typeof import("../../node_modules/@varlet/ui/es/loading-bar/index")['_LoadingBarComponent']
    'VarLoadingBarStyle': typeof import("../../node_modules/@varlet/ui/es/loading-bar/style/index")['_LoadingBarStyleComponent']
    'VarLoading': typeof import("../../node_modules/@varlet/ui/es/loading/index")['_LoadingComponent']
    'VarLoadingStyle': typeof import("../../node_modules/@varlet/ui/es/loading/style/index")['_LoadingStyleComponent']
    'VarLocaleProvider': typeof import("../../node_modules/@varlet/ui/es/locale-provider/index")['_LocaleProviderComponent']
    'VarLocaleProviderStyle': typeof import("../../node_modules/@varlet/ui/es/locale-provider/style/index")['_LocaleProviderStyleComponent']
    'VarLocale': typeof import("../../node_modules/@varlet/ui/es/locale/index")['_LocaleComponent']
    'VarLocaleStyle': typeof import("../../node_modules/@varlet/ui/es/locale/style/index")['_LocaleStyleComponent']
    'VarMenuOption': typeof import("../../node_modules/@varlet/ui/es/menu-option/index")['_MenuOptionComponent']
    'VarMenuOptionStyle': typeof import("../../node_modules/@varlet/ui/es/menu-option/style/index")['_MenuOptionStyleComponent']
    'VarMenuSelect': typeof import("../../node_modules/@varlet/ui/es/menu-select/index")['_MenuSelectComponent']
    'VarMenuSelectStyle': typeof import("../../node_modules/@varlet/ui/es/menu-select/style/index")['_MenuSelectStyleComponent']
    'VarMenu': typeof import("../../node_modules/@varlet/ui/es/menu/index")['_MenuComponent']
    'VarMenuStyle': typeof import("../../node_modules/@varlet/ui/es/menu/style/index")['_MenuStyleComponent']
    'VarOption': typeof import("../../node_modules/@varlet/ui/es/option/index")['_OptionComponent']
    'VarOptionStyle': typeof import("../../node_modules/@varlet/ui/es/option/style/index")['_OptionStyleComponent']
    'VarOverlay': typeof import("../../node_modules/@varlet/ui/es/overlay/index")['_OverlayComponent']
    'VarOverlayStyle': typeof import("../../node_modules/@varlet/ui/es/overlay/style/index")['_OverlayStyleComponent']
    'VarPagination': typeof import("../../node_modules/@varlet/ui/es/pagination/index")['_PaginationComponent']
    'VarPaginationStyle': typeof import("../../node_modules/@varlet/ui/es/pagination/style/index")['_PaginationStyleComponent']
    'VarPaper': typeof import("../../node_modules/@varlet/ui/es/paper/index")['_PaperComponent']
    'VarPaperStyle': typeof import("../../node_modules/@varlet/ui/es/paper/style/index")['_PaperStyleComponent']
    'VarPicker': typeof import("../../node_modules/@varlet/ui/es/picker/index")['_PickerComponent']
    'VarPickerStyle': typeof import("../../node_modules/@varlet/ui/es/picker/style/index")['_PickerStyleComponent']
    'VarPopup': typeof import("../../node_modules/@varlet/ui/es/popup/index")['_PopupComponent']
    'VarPopupStyle': typeof import("../../node_modules/@varlet/ui/es/popup/style/index")['_PopupStyleComponent']
    'VarProgress': typeof import("../../node_modules/@varlet/ui/es/progress/index")['_ProgressComponent']
    'VarProgressStyle': typeof import("../../node_modules/@varlet/ui/es/progress/style/index")['_ProgressStyleComponent']
    'VarPullRefresh': typeof import("../../node_modules/@varlet/ui/es/pull-refresh/index")['_PullRefreshComponent']
    'VarPullRefreshStyle': typeof import("../../node_modules/@varlet/ui/es/pull-refresh/style/index")['_PullRefreshStyleComponent']
    'VarRadioGroup': typeof import("../../node_modules/@varlet/ui/es/radio-group/index")['_RadioGroupComponent']
    'VarRadioGroupStyle': typeof import("../../node_modules/@varlet/ui/es/radio-group/style/index")['_RadioGroupStyleComponent']
    'VarRadio': typeof import("../../node_modules/@varlet/ui/es/radio/index")['_RadioComponent']
    'VarRadioStyle': typeof import("../../node_modules/@varlet/ui/es/radio/style/index")['_RadioStyleComponent']
    'VarRate': typeof import("../../node_modules/@varlet/ui/es/rate/index")['_RateComponent']
    'VarRateStyle': typeof import("../../node_modules/@varlet/ui/es/rate/style/index")['_RateStyleComponent']
    'VarResult': typeof import("../../node_modules/@varlet/ui/es/result/index")['_ResultComponent']
    'VarResultStyle': typeof import("../../node_modules/@varlet/ui/es/result/style/index")['_ResultStyleComponent']
    'VarRipple': typeof import("../../node_modules/@varlet/ui/es/ripple/index")['_RippleComponent']
    'VarRippleStyle': typeof import("../../node_modules/@varlet/ui/es/ripple/style/index")['_RippleStyleComponent']
    'VarRow': typeof import("../../node_modules/@varlet/ui/es/row/index")['_RowComponent']
    'VarRowStyle': typeof import("../../node_modules/@varlet/ui/es/row/style/index")['_RowStyleComponent']
    'VarSelect': typeof import("../../node_modules/@varlet/ui/es/select/index")['_SelectComponent']
    'VarSelectStyle': typeof import("../../node_modules/@varlet/ui/es/select/style/index")['_SelectStyleComponent']
    'VarSignature': typeof import("../../node_modules/@varlet/ui/es/signature/index")['_SignatureComponent']
    'VarSignatureStyle': typeof import("../../node_modules/@varlet/ui/es/signature/style/index")['_SignatureStyleComponent']
    'VarSkeleton': typeof import("../../node_modules/@varlet/ui/es/skeleton/index")['_SkeletonComponent']
    'VarSkeletonStyle': typeof import("../../node_modules/@varlet/ui/es/skeleton/style/index")['_SkeletonStyleComponent']
    'VarSlider': typeof import("../../node_modules/@varlet/ui/es/slider/index")['_SliderComponent']
    'VarSliderStyle': typeof import("../../node_modules/@varlet/ui/es/slider/style/index")['_SliderStyleComponent']
    'VarSnackbar': typeof import("../../node_modules/@varlet/ui/es/snackbar/index")['_SnackbarComponent']
    'VarSnackbarStyle': typeof import("../../node_modules/@varlet/ui/es/snackbar/style/index")['_SnackbarStyleComponent']
    'VarSpace': typeof import("../../node_modules/@varlet/ui/es/space/index")['_SpaceComponent']
    'VarSpaceStyle': typeof import("../../node_modules/@varlet/ui/es/space/style/index")['_SpaceStyleComponent']
    'VarStep': typeof import("../../node_modules/@varlet/ui/es/step/index")['_StepComponent']
    'VarStepStyle': typeof import("../../node_modules/@varlet/ui/es/step/style/index")['_StepStyleComponent']
    'VarSteps': typeof import("../../node_modules/@varlet/ui/es/steps/index")['_StepsComponent']
    'VarStepsStyle': typeof import("../../node_modules/@varlet/ui/es/steps/style/index")['_StepsStyleComponent']
    'VarSticky': typeof import("../../node_modules/@varlet/ui/es/sticky/index")['_StickyComponent']
    'VarStickyStyle': typeof import("../../node_modules/@varlet/ui/es/sticky/style/index")['_StickyStyleComponent']
    'VarStyleProvider': typeof import("../../node_modules/@varlet/ui/es/style-provider/index")['_StyleProviderComponent']
    'VarStyleProviderStyle': typeof import("../../node_modules/@varlet/ui/es/style-provider/style/index")['_StyleProviderStyleComponent']
    'VarStylesStyle': typeof import("../../node_modules/@varlet/ui/es/styles/style/index")['_StylesStyleComponent']
    'VarSwipeItem': typeof import("../../node_modules/@varlet/ui/es/swipe-item/index")['_SwipeItemComponent']
    'VarSwipeItemStyle': typeof import("../../node_modules/@varlet/ui/es/swipe-item/style/index")['_SwipeItemStyleComponent']
    'VarSwipe': typeof import("../../node_modules/@varlet/ui/es/swipe/index")['_SwipeComponent']
    'VarSwipeStyle': typeof import("../../node_modules/@varlet/ui/es/swipe/style/index")['_SwipeStyleComponent']
    'VarSwitch': typeof import("../../node_modules/@varlet/ui/es/switch/index")['_SwitchComponent']
    'VarSwitchStyle': typeof import("../../node_modules/@varlet/ui/es/switch/style/index")['_SwitchStyleComponent']
    'VarTabItem': typeof import("../../node_modules/@varlet/ui/es/tab-item/index")['_TabItemComponent']
    'VarTabItemStyle': typeof import("../../node_modules/@varlet/ui/es/tab-item/style/index")['_TabItemStyleComponent']
    'VarTab': typeof import("../../node_modules/@varlet/ui/es/tab/index")['_TabComponent']
    'VarTabStyle': typeof import("../../node_modules/@varlet/ui/es/tab/style/index")['_TabStyleComponent']
    'VarTable': typeof import("../../node_modules/@varlet/ui/es/table/index")['_TableComponent']
    'VarTableStyle': typeof import("../../node_modules/@varlet/ui/es/table/style/index")['_TableStyleComponent']
    'VarTabsItems': typeof import("../../node_modules/@varlet/ui/es/tabs-items/index")['_TabsItemsComponent']
    'VarTabsItemsStyle': typeof import("../../node_modules/@varlet/ui/es/tabs-items/style/index")['_TabsItemsStyleComponent']
    'VarTabs': typeof import("../../node_modules/@varlet/ui/es/tabs/index")['_TabsComponent']
    'VarTabsStyle': typeof import("../../node_modules/@varlet/ui/es/tabs/style/index")['_TabsStyleComponent']
    'VarThemesDark': typeof import("../../node_modules/@varlet/ui/es/themes/dark/index")['_ThemesDarkComponent']
    'VarThemes': typeof import("../../node_modules/@varlet/ui/es/themes/index")['_ThemesComponent']
    'VarThemesMd3Dark': typeof import("../../node_modules/@varlet/ui/es/themes/md3-dark/index")['_ThemesMd3DarkComponent']
    'VarThemesMd3Light': typeof import("../../node_modules/@varlet/ui/es/themes/md3-light/index")['_ThemesMd3LightComponent']
    'VarThemesStyle': typeof import("../../node_modules/@varlet/ui/es/themes/style/index")['_ThemesStyleComponent']
    'VarTimePicker': typeof import("../../node_modules/@varlet/ui/es/time-picker/index")['_TimePickerComponent']
    'VarTimePickerStyle': typeof import("../../node_modules/@varlet/ui/es/time-picker/style/index")['_TimePickerStyleComponent']
    'VarTooltip': typeof import("../../node_modules/@varlet/ui/es/tooltip/index")['_TooltipComponent']
    'VarTooltipStyle': typeof import("../../node_modules/@varlet/ui/es/tooltip/style/index")['_TooltipStyleComponent']
    'VarUploader': typeof import("../../node_modules/@varlet/ui/es/uploader/index")['_UploaderComponent']
    'VarUploaderStyle': typeof import("../../node_modules/@varlet/ui/es/uploader/style/index")['_UploaderStyleComponent']
    'VarUtilsStyle': typeof import("../../node_modules/@varlet/ui/es/utils/style/index")['_UtilsStyleComponent']
    'VarWatermark': typeof import("../../node_modules/@varlet/ui/es/watermark/index")['_WatermarkComponent']
    'VarWatermarkStyle': typeof import("../../node_modules/@varlet/ui/es/watermark/style/index")['_WatermarkStyleComponent']
    'NuxtWelcome': typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
    'ClientOnly': typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtTime': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'VitePwaManifest': typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaManifest': typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
    'NuxtPwaAssets': typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
    'PwaAppleImage': typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
    'PwaAppleSplashScreenImage': typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
    'PwaFaviconImage': typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
    'PwaMaskableImage': typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
    'PwaTransparentImage': typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
    'NuxtPage': typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']
      'LazyVarActionSheet': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/action-sheet/index")['_ActionSheetComponent']>
    'LazyVarActionSheetStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/action-sheet/style/index")['_ActionSheetStyleComponent']>
    'LazyVarAlert': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/alert/index")['_AlertComponent']>
    'LazyVarAlertStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/alert/style/index")['_AlertStyleComponent']>
    'LazyVarAppBar': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/app-bar/index")['_AppBarComponent']>
    'LazyVarAppBarStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/app-bar/style/index")['_AppBarStyleComponent']>
    'LazyVarAutoComplete': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/auto-complete/index")['_AutoCompleteComponent']>
    'LazyVarAutoCompleteStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/auto-complete/style/index")['_AutoCompleteStyleComponent']>
    'LazyVarAvatarGroup': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/avatar-group/index")['_AvatarGroupComponent']>
    'LazyVarAvatarGroupStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/avatar-group/style/index")['_AvatarGroupStyleComponent']>
    'LazyVarAvatar': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/avatar/index")['_AvatarComponent']>
    'LazyVarAvatarStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/avatar/style/index")['_AvatarStyleComponent']>
    'LazyVarBackTop': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/back-top/index")['_BackTopComponent']>
    'LazyVarBackTopStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/back-top/style/index")['_BackTopStyleComponent']>
    'LazyVarBadge': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/badge/index")['_BadgeComponent']>
    'LazyVarBadgeStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/badge/style/index")['_BadgeStyleComponent']>
    'LazyVarBottomNavigationItem': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/bottom-navigation-item/index")['_BottomNavigationItemComponent']>
    'LazyVarBottomNavigationItemStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/bottom-navigation-item/style/index")['_BottomNavigationItemStyleComponent']>
    'LazyVarBottomNavigation': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/bottom-navigation/index")['_BottomNavigationComponent']>
    'LazyVarBottomNavigationStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/bottom-navigation/style/index")['_BottomNavigationStyleComponent']>
    'LazyVarBreadcrumb': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/breadcrumb/index")['_BreadcrumbComponent']>
    'LazyVarBreadcrumbStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/breadcrumb/style/index")['_BreadcrumbStyleComponent']>
    'LazyVarBreadcrumbs': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/breadcrumbs/index")['_BreadcrumbsComponent']>
    'LazyVarBreadcrumbsStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/breadcrumbs/style/index")['_BreadcrumbsStyleComponent']>
    'LazyVarButtonGroup': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/button-group/index")['_ButtonGroupComponent']>
    'LazyVarButtonGroupStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/button-group/style/index")['_ButtonGroupStyleComponent']>
    'LazyVarButton': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/button/index")['_ButtonComponent']>
    'LazyVarButtonStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/button/style/index")['_ButtonStyleComponent']>
    'LazyVarCard': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/card/index")['_CardComponent']>
    'LazyVarCardStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/card/style/index")['_CardStyleComponent']>
    'LazyVarCell': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/cell/index")['_CellComponent']>
    'LazyVarCellStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/cell/style/index")['_CellStyleComponent']>
    'LazyVarCheckboxGroup': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/checkbox-group/index")['_CheckboxGroupComponent']>
    'LazyVarCheckboxGroupStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/checkbox-group/style/index")['_CheckboxGroupStyleComponent']>
    'LazyVarCheckbox': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/checkbox/index")['_CheckboxComponent']>
    'LazyVarCheckboxStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/checkbox/style/index")['_CheckboxStyleComponent']>
    'LazyVarChip': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/chip/index")['_ChipComponent']>
    'LazyVarChipStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/chip/style/index")['_ChipStyleComponent']>
    'LazyVarCode': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/code/index")['_CodeComponent']>
    'LazyVarCodeStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/code/style/index")['_CodeStyleComponent']>
    'LazyVarCol': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/col/index")['_ColComponent']>
    'LazyVarColStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/col/style/index")['_ColStyleComponent']>
    'LazyVarCollapseItem': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/collapse-item/index")['_CollapseItemComponent']>
    'LazyVarCollapseItemStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/collapse-item/style/index")['_CollapseItemStyleComponent']>
    'LazyVarCollapseTransition': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/collapse-transition/index")['_CollapseTransitionComponent']>
    'LazyVarCollapseTransitionStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/collapse-transition/style/index")['_CollapseTransitionStyleComponent']>
    'LazyVarCollapse': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/collapse/index")['_CollapseComponent']>
    'LazyVarCollapseStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/collapse/style/index")['_CollapseStyleComponent']>
    'LazyVarContext': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/context/index")['_ContextComponent']>
    'LazyVarContextStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/context/style/index")['_ContextStyleComponent']>
    'LazyVarCountTo': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/count-to/index")['_CountToComponent']>
    'LazyVarCountToStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/count-to/style/index")['_CountToStyleComponent']>
    'LazyVarCountdown': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/countdown/index")['_CountdownComponent']>
    'LazyVarCountdownStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/countdown/style/index")['_CountdownStyleComponent']>
    'LazyVarCounter': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/counter/index")['_CounterComponent']>
    'LazyVarCounterStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/counter/style/index")['_CounterStyleComponent']>
    'LazyVarDatePicker': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/date-picker/index")['_DatePickerComponent']>
    'LazyVarDatePickerStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/date-picker/style/index")['_DatePickerStyleComponent']>
    'LazyVarDialog': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/dialog/index")['_DialogComponent']>
    'LazyVarDialogStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/dialog/style/index")['_DialogStyleComponent']>
    'LazyVarDivider': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/divider/index")['_DividerComponent']>
    'LazyVarDividerStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/divider/style/index")['_DividerStyleComponent']>
    'LazyVarDrag': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/drag/index")['_DragComponent']>
    'LazyVarDragStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/drag/style/index")['_DragStyleComponent']>
    'LazyVarEllipsis': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/ellipsis/index")['_EllipsisComponent']>
    'LazyVarEllipsisStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/ellipsis/style/index")['_EllipsisStyleComponent']>
    'LazyVarFab': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/fab/index")['_FabComponent']>
    'LazyVarFabStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/fab/style/index")['_FabStyleComponent']>
    'LazyVarFieldDecorator': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/field-decorator/index")['_FieldDecoratorComponent']>
    'LazyVarFieldDecoratorStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/field-decorator/style/index")['_FieldDecoratorStyleComponent']>
    'LazyVarFloatingPanel': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/floating-panel/index")['_FloatingPanelComponent']>
    'LazyVarFloatingPanelStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/floating-panel/style/index")['_FloatingPanelStyleComponent']>
    'LazyVarFormDetails': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/form-details/index")['_FormDetailsComponent']>
    'LazyVarFormDetailsStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/form-details/style/index")['_FormDetailsStyleComponent']>
    'LazyVarForm': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/form/index")['_FormComponent']>
    'LazyVarFormStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/form/style/index")['_FormStyleComponent']>
    'LazyVarHighlighterProvider': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/highlighter-provider/index")['_HighlighterProviderComponent']>
    'LazyVarHighlighterProviderStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/highlighter-provider/style/index")['_HighlighterProviderStyleComponent']>
    'LazyVarHoverOverlay': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/hover-overlay/index")['_HoverOverlayComponent']>
    'LazyVarHoverOverlayStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/hover-overlay/style/index")['_HoverOverlayStyleComponent']>
    'LazyVarHover': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/hover/index")['_HoverComponent']>
    'LazyVarHoverStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/hover/style/index")['_HoverStyleComponent']>
    'LazyVarIcon': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/icon/index")['_IconComponent']>
    'LazyVarIconStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/icon/style/index")['_IconStyleComponent']>
    'LazyVarImagePreview': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/image-preview/index")['_ImagePreviewComponent']>
    'LazyVarImagePreviewStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/image-preview/style/index")['_ImagePreviewStyleComponent']>
    'LazyVarImage': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/image/index")['_ImageComponent']>
    'LazyVarImageStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/image/style/index")['_ImageStyleComponent']>
    'LazyVarIndexAnchor': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/index-anchor/index")['_IndexAnchorComponent']>
    'LazyVarIndexAnchorStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/index-anchor/style/index")['_IndexAnchorStyleComponent']>
    'LazyVarIndexBar': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/index-bar/index")['_IndexBarComponent']>
    'LazyVarIndexBarStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/index-bar/style/index")['_IndexBarStyleComponent']>
    'LazyVarIndexBundle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/index.bundle")['_IndexBundleComponent']>
    'LazyVar': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/index")['_Component']>
    'LazyVarInput': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/input/index")['_InputComponent']>
    'LazyVarInputStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/input/style/index")['_InputStyleComponent']>
    'LazyVarLazy': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/lazy/index")['_LazyComponent']>
    'LazyVarLazyStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/lazy/style/index")['_LazyStyleComponent']>
    'LazyVarLink': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/link/index")['_LinkComponent']>
    'LazyVarLinkStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/link/style/index")['_LinkStyleComponent']>
    'LazyVarList': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/list/index")['_ListComponent']>
    'LazyVarListStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/list/style/index")['_ListStyleComponent']>
    'LazyVarLoadingBar': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/loading-bar/index")['_LoadingBarComponent']>
    'LazyVarLoadingBarStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/loading-bar/style/index")['_LoadingBarStyleComponent']>
    'LazyVarLoading': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/loading/index")['_LoadingComponent']>
    'LazyVarLoadingStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/loading/style/index")['_LoadingStyleComponent']>
    'LazyVarLocaleProvider': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/locale-provider/index")['_LocaleProviderComponent']>
    'LazyVarLocaleProviderStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/locale-provider/style/index")['_LocaleProviderStyleComponent']>
    'LazyVarLocale': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/locale/index")['_LocaleComponent']>
    'LazyVarLocaleStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/locale/style/index")['_LocaleStyleComponent']>
    'LazyVarMenuOption': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/menu-option/index")['_MenuOptionComponent']>
    'LazyVarMenuOptionStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/menu-option/style/index")['_MenuOptionStyleComponent']>
    'LazyVarMenuSelect': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/menu-select/index")['_MenuSelectComponent']>
    'LazyVarMenuSelectStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/menu-select/style/index")['_MenuSelectStyleComponent']>
    'LazyVarMenu': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/menu/index")['_MenuComponent']>
    'LazyVarMenuStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/menu/style/index")['_MenuStyleComponent']>
    'LazyVarOption': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/option/index")['_OptionComponent']>
    'LazyVarOptionStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/option/style/index")['_OptionStyleComponent']>
    'LazyVarOverlay': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/overlay/index")['_OverlayComponent']>
    'LazyVarOverlayStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/overlay/style/index")['_OverlayStyleComponent']>
    'LazyVarPagination': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/pagination/index")['_PaginationComponent']>
    'LazyVarPaginationStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/pagination/style/index")['_PaginationStyleComponent']>
    'LazyVarPaper': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/paper/index")['_PaperComponent']>
    'LazyVarPaperStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/paper/style/index")['_PaperStyleComponent']>
    'LazyVarPicker': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/picker/index")['_PickerComponent']>
    'LazyVarPickerStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/picker/style/index")['_PickerStyleComponent']>
    'LazyVarPopup': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/popup/index")['_PopupComponent']>
    'LazyVarPopupStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/popup/style/index")['_PopupStyleComponent']>
    'LazyVarProgress': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/progress/index")['_ProgressComponent']>
    'LazyVarProgressStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/progress/style/index")['_ProgressStyleComponent']>
    'LazyVarPullRefresh': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/pull-refresh/index")['_PullRefreshComponent']>
    'LazyVarPullRefreshStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/pull-refresh/style/index")['_PullRefreshStyleComponent']>
    'LazyVarRadioGroup': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/radio-group/index")['_RadioGroupComponent']>
    'LazyVarRadioGroupStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/radio-group/style/index")['_RadioGroupStyleComponent']>
    'LazyVarRadio': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/radio/index")['_RadioComponent']>
    'LazyVarRadioStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/radio/style/index")['_RadioStyleComponent']>
    'LazyVarRate': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/rate/index")['_RateComponent']>
    'LazyVarRateStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/rate/style/index")['_RateStyleComponent']>
    'LazyVarResult': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/result/index")['_ResultComponent']>
    'LazyVarResultStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/result/style/index")['_ResultStyleComponent']>
    'LazyVarRipple': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/ripple/index")['_RippleComponent']>
    'LazyVarRippleStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/ripple/style/index")['_RippleStyleComponent']>
    'LazyVarRow': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/row/index")['_RowComponent']>
    'LazyVarRowStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/row/style/index")['_RowStyleComponent']>
    'LazyVarSelect': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/select/index")['_SelectComponent']>
    'LazyVarSelectStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/select/style/index")['_SelectStyleComponent']>
    'LazyVarSignature': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/signature/index")['_SignatureComponent']>
    'LazyVarSignatureStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/signature/style/index")['_SignatureStyleComponent']>
    'LazyVarSkeleton': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/skeleton/index")['_SkeletonComponent']>
    'LazyVarSkeletonStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/skeleton/style/index")['_SkeletonStyleComponent']>
    'LazyVarSlider': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/slider/index")['_SliderComponent']>
    'LazyVarSliderStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/slider/style/index")['_SliderStyleComponent']>
    'LazyVarSnackbar': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/snackbar/index")['_SnackbarComponent']>
    'LazyVarSnackbarStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/snackbar/style/index")['_SnackbarStyleComponent']>
    'LazyVarSpace': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/space/index")['_SpaceComponent']>
    'LazyVarSpaceStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/space/style/index")['_SpaceStyleComponent']>
    'LazyVarStep': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/step/index")['_StepComponent']>
    'LazyVarStepStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/step/style/index")['_StepStyleComponent']>
    'LazyVarSteps': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/steps/index")['_StepsComponent']>
    'LazyVarStepsStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/steps/style/index")['_StepsStyleComponent']>
    'LazyVarSticky': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/sticky/index")['_StickyComponent']>
    'LazyVarStickyStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/sticky/style/index")['_StickyStyleComponent']>
    'LazyVarStyleProvider': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/style-provider/index")['_StyleProviderComponent']>
    'LazyVarStyleProviderStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/style-provider/style/index")['_StyleProviderStyleComponent']>
    'LazyVarStylesStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/styles/style/index")['_StylesStyleComponent']>
    'LazyVarSwipeItem': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/swipe-item/index")['_SwipeItemComponent']>
    'LazyVarSwipeItemStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/swipe-item/style/index")['_SwipeItemStyleComponent']>
    'LazyVarSwipe': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/swipe/index")['_SwipeComponent']>
    'LazyVarSwipeStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/swipe/style/index")['_SwipeStyleComponent']>
    'LazyVarSwitch': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/switch/index")['_SwitchComponent']>
    'LazyVarSwitchStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/switch/style/index")['_SwitchStyleComponent']>
    'LazyVarTabItem': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/tab-item/index")['_TabItemComponent']>
    'LazyVarTabItemStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/tab-item/style/index")['_TabItemStyleComponent']>
    'LazyVarTab': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/tab/index")['_TabComponent']>
    'LazyVarTabStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/tab/style/index")['_TabStyleComponent']>
    'LazyVarTable': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/table/index")['_TableComponent']>
    'LazyVarTableStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/table/style/index")['_TableStyleComponent']>
    'LazyVarTabsItems': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/tabs-items/index")['_TabsItemsComponent']>
    'LazyVarTabsItemsStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/tabs-items/style/index")['_TabsItemsStyleComponent']>
    'LazyVarTabs': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/tabs/index")['_TabsComponent']>
    'LazyVarTabsStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/tabs/style/index")['_TabsStyleComponent']>
    'LazyVarThemesDark': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/themes/dark/index")['_ThemesDarkComponent']>
    'LazyVarThemes': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/themes/index")['_ThemesComponent']>
    'LazyVarThemesMd3Dark': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/themes/md3-dark/index")['_ThemesMd3DarkComponent']>
    'LazyVarThemesMd3Light': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/themes/md3-light/index")['_ThemesMd3LightComponent']>
    'LazyVarThemesStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/themes/style/index")['_ThemesStyleComponent']>
    'LazyVarTimePicker': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/time-picker/index")['_TimePickerComponent']>
    'LazyVarTimePickerStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/time-picker/style/index")['_TimePickerStyleComponent']>
    'LazyVarTooltip': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/tooltip/index")['_TooltipComponent']>
    'LazyVarTooltipStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/tooltip/style/index")['_TooltipStyleComponent']>
    'LazyVarUploader': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/uploader/index")['_UploaderComponent']>
    'LazyVarUploaderStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/uploader/style/index")['_UploaderStyleComponent']>
    'LazyVarUtilsStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/utils/style/index")['_UtilsStyleComponent']>
    'LazyVarWatermark': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/watermark/index")['_WatermarkComponent']>
    'LazyVarWatermarkStyle': LazyComponent<typeof import("../../node_modules/@varlet/ui/es/watermark/style/index")['_WatermarkStyleComponent']>
    'LazyNuxtWelcome': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
    'LazyNuxtLayout': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
    'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
    'LazyClientOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/client-only")['default']>
    'LazyDevOnly': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/dev-only")['default']>
    'LazyServerPlaceholder': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
    'LazyNuxtLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
    'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
    'LazyNuxtTime': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
    'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
    'LazyNuxtImg': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
    'LazyNuxtPicture': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
    'LazyVitePwaManifest': LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
    'LazyNuxtPwaManifest': LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
    'LazyNuxtPwaAssets': LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
    'LazyPwaAppleImage': LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']>
    'LazyPwaAppleSplashScreenImage': LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']>
    'LazyPwaFaviconImage': LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']>
    'LazyPwaMaskableImage': LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']>
    'LazyPwaTransparentImage': LazyComponent<typeof import("../../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']>
    'LazyNuxtPage': LazyComponent<typeof import("../../node_modules/nuxt/dist/pages/runtime/page")['default']>
    'LazyNoScript': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
    'LazyLink': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Link']>
    'LazyBase': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Base']>
    'LazyTitle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Title']>
    'LazyMeta': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Meta']>
    'LazyStyle': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Style']>
    'LazyHead': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Head']>
    'LazyHtml': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Html']>
    'LazyBody': LazyComponent<typeof import("../../node_modules/nuxt/dist/head/runtime/components")['Body']>
    'LazyNuxtIsland': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
    'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
