
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = (T & DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }>)


export const VarActionSheet: typeof import("../node_modules/@varlet/ui/es/action-sheet/index")['_ActionSheetComponent']
export const VarActionSheetStyle: typeof import("../node_modules/@varlet/ui/es/action-sheet/style/index")['_ActionSheetStyleComponent']
export const VarAlert: typeof import("../node_modules/@varlet/ui/es/alert/index")['_AlertComponent']
export const VarAlertStyle: typeof import("../node_modules/@varlet/ui/es/alert/style/index")['_AlertStyleComponent']
export const VarAppBar: typeof import("../node_modules/@varlet/ui/es/app-bar/index")['_AppBarComponent']
export const VarAppBarStyle: typeof import("../node_modules/@varlet/ui/es/app-bar/style/index")['_AppBarStyleComponent']
export const VarAutoComplete: typeof import("../node_modules/@varlet/ui/es/auto-complete/index")['_AutoCompleteComponent']
export const VarAutoCompleteStyle: typeof import("../node_modules/@varlet/ui/es/auto-complete/style/index")['_AutoCompleteStyleComponent']
export const VarAvatarGroup: typeof import("../node_modules/@varlet/ui/es/avatar-group/index")['_AvatarGroupComponent']
export const VarAvatarGroupStyle: typeof import("../node_modules/@varlet/ui/es/avatar-group/style/index")['_AvatarGroupStyleComponent']
export const VarAvatar: typeof import("../node_modules/@varlet/ui/es/avatar/index")['_AvatarComponent']
export const VarAvatarStyle: typeof import("../node_modules/@varlet/ui/es/avatar/style/index")['_AvatarStyleComponent']
export const VarBackTop: typeof import("../node_modules/@varlet/ui/es/back-top/index")['_BackTopComponent']
export const VarBackTopStyle: typeof import("../node_modules/@varlet/ui/es/back-top/style/index")['_BackTopStyleComponent']
export const VarBadge: typeof import("../node_modules/@varlet/ui/es/badge/index")['_BadgeComponent']
export const VarBadgeStyle: typeof import("../node_modules/@varlet/ui/es/badge/style/index")['_BadgeStyleComponent']
export const VarBottomNavigationItem: typeof import("../node_modules/@varlet/ui/es/bottom-navigation-item/index")['_BottomNavigationItemComponent']
export const VarBottomNavigationItemStyle: typeof import("../node_modules/@varlet/ui/es/bottom-navigation-item/style/index")['_BottomNavigationItemStyleComponent']
export const VarBottomNavigation: typeof import("../node_modules/@varlet/ui/es/bottom-navigation/index")['_BottomNavigationComponent']
export const VarBottomNavigationStyle: typeof import("../node_modules/@varlet/ui/es/bottom-navigation/style/index")['_BottomNavigationStyleComponent']
export const VarBreadcrumb: typeof import("../node_modules/@varlet/ui/es/breadcrumb/index")['_BreadcrumbComponent']
export const VarBreadcrumbStyle: typeof import("../node_modules/@varlet/ui/es/breadcrumb/style/index")['_BreadcrumbStyleComponent']
export const VarBreadcrumbs: typeof import("../node_modules/@varlet/ui/es/breadcrumbs/index")['_BreadcrumbsComponent']
export const VarBreadcrumbsStyle: typeof import("../node_modules/@varlet/ui/es/breadcrumbs/style/index")['_BreadcrumbsStyleComponent']
export const VarButtonGroup: typeof import("../node_modules/@varlet/ui/es/button-group/index")['_ButtonGroupComponent']
export const VarButtonGroupStyle: typeof import("../node_modules/@varlet/ui/es/button-group/style/index")['_ButtonGroupStyleComponent']
export const VarButton: typeof import("../node_modules/@varlet/ui/es/button/index")['_ButtonComponent']
export const VarButtonStyle: typeof import("../node_modules/@varlet/ui/es/button/style/index")['_ButtonStyleComponent']
export const VarCard: typeof import("../node_modules/@varlet/ui/es/card/index")['_CardComponent']
export const VarCardStyle: typeof import("../node_modules/@varlet/ui/es/card/style/index")['_CardStyleComponent']
export const VarCell: typeof import("../node_modules/@varlet/ui/es/cell/index")['_CellComponent']
export const VarCellStyle: typeof import("../node_modules/@varlet/ui/es/cell/style/index")['_CellStyleComponent']
export const VarCheckboxGroup: typeof import("../node_modules/@varlet/ui/es/checkbox-group/index")['_CheckboxGroupComponent']
export const VarCheckboxGroupStyle: typeof import("../node_modules/@varlet/ui/es/checkbox-group/style/index")['_CheckboxGroupStyleComponent']
export const VarCheckbox: typeof import("../node_modules/@varlet/ui/es/checkbox/index")['_CheckboxComponent']
export const VarCheckboxStyle: typeof import("../node_modules/@varlet/ui/es/checkbox/style/index")['_CheckboxStyleComponent']
export const VarChip: typeof import("../node_modules/@varlet/ui/es/chip/index")['_ChipComponent']
export const VarChipStyle: typeof import("../node_modules/@varlet/ui/es/chip/style/index")['_ChipStyleComponent']
export const VarCode: typeof import("../node_modules/@varlet/ui/es/code/index")['_CodeComponent']
export const VarCodeStyle: typeof import("../node_modules/@varlet/ui/es/code/style/index")['_CodeStyleComponent']
export const VarCol: typeof import("../node_modules/@varlet/ui/es/col/index")['_ColComponent']
export const VarColStyle: typeof import("../node_modules/@varlet/ui/es/col/style/index")['_ColStyleComponent']
export const VarCollapseItem: typeof import("../node_modules/@varlet/ui/es/collapse-item/index")['_CollapseItemComponent']
export const VarCollapseItemStyle: typeof import("../node_modules/@varlet/ui/es/collapse-item/style/index")['_CollapseItemStyleComponent']
export const VarCollapseTransition: typeof import("../node_modules/@varlet/ui/es/collapse-transition/index")['_CollapseTransitionComponent']
export const VarCollapseTransitionStyle: typeof import("../node_modules/@varlet/ui/es/collapse-transition/style/index")['_CollapseTransitionStyleComponent']
export const VarCollapse: typeof import("../node_modules/@varlet/ui/es/collapse/index")['_CollapseComponent']
export const VarCollapseStyle: typeof import("../node_modules/@varlet/ui/es/collapse/style/index")['_CollapseStyleComponent']
export const VarContext: typeof import("../node_modules/@varlet/ui/es/context/index")['_ContextComponent']
export const VarContextStyle: typeof import("../node_modules/@varlet/ui/es/context/style/index")['_ContextStyleComponent']
export const VarCountTo: typeof import("../node_modules/@varlet/ui/es/count-to/index")['_CountToComponent']
export const VarCountToStyle: typeof import("../node_modules/@varlet/ui/es/count-to/style/index")['_CountToStyleComponent']
export const VarCountdown: typeof import("../node_modules/@varlet/ui/es/countdown/index")['_CountdownComponent']
export const VarCountdownStyle: typeof import("../node_modules/@varlet/ui/es/countdown/style/index")['_CountdownStyleComponent']
export const VarCounter: typeof import("../node_modules/@varlet/ui/es/counter/index")['_CounterComponent']
export const VarCounterStyle: typeof import("../node_modules/@varlet/ui/es/counter/style/index")['_CounterStyleComponent']
export const VarDatePicker: typeof import("../node_modules/@varlet/ui/es/date-picker/index")['_DatePickerComponent']
export const VarDatePickerStyle: typeof import("../node_modules/@varlet/ui/es/date-picker/style/index")['_DatePickerStyleComponent']
export const VarDialog: typeof import("../node_modules/@varlet/ui/es/dialog/index")['_DialogComponent']
export const VarDialogStyle: typeof import("../node_modules/@varlet/ui/es/dialog/style/index")['_DialogStyleComponent']
export const VarDivider: typeof import("../node_modules/@varlet/ui/es/divider/index")['_DividerComponent']
export const VarDividerStyle: typeof import("../node_modules/@varlet/ui/es/divider/style/index")['_DividerStyleComponent']
export const VarDrag: typeof import("../node_modules/@varlet/ui/es/drag/index")['_DragComponent']
export const VarDragStyle: typeof import("../node_modules/@varlet/ui/es/drag/style/index")['_DragStyleComponent']
export const VarEllipsis: typeof import("../node_modules/@varlet/ui/es/ellipsis/index")['_EllipsisComponent']
export const VarEllipsisStyle: typeof import("../node_modules/@varlet/ui/es/ellipsis/style/index")['_EllipsisStyleComponent']
export const VarFab: typeof import("../node_modules/@varlet/ui/es/fab/index")['_FabComponent']
export const VarFabStyle: typeof import("../node_modules/@varlet/ui/es/fab/style/index")['_FabStyleComponent']
export const VarFieldDecorator: typeof import("../node_modules/@varlet/ui/es/field-decorator/index")['_FieldDecoratorComponent']
export const VarFieldDecoratorStyle: typeof import("../node_modules/@varlet/ui/es/field-decorator/style/index")['_FieldDecoratorStyleComponent']
export const VarFloatingPanel: typeof import("../node_modules/@varlet/ui/es/floating-panel/index")['_FloatingPanelComponent']
export const VarFloatingPanelStyle: typeof import("../node_modules/@varlet/ui/es/floating-panel/style/index")['_FloatingPanelStyleComponent']
export const VarFormDetails: typeof import("../node_modules/@varlet/ui/es/form-details/index")['_FormDetailsComponent']
export const VarFormDetailsStyle: typeof import("../node_modules/@varlet/ui/es/form-details/style/index")['_FormDetailsStyleComponent']
export const VarForm: typeof import("../node_modules/@varlet/ui/es/form/index")['_FormComponent']
export const VarFormStyle: typeof import("../node_modules/@varlet/ui/es/form/style/index")['_FormStyleComponent']
export const VarHighlighterProvider: typeof import("../node_modules/@varlet/ui/es/highlighter-provider/index")['_HighlighterProviderComponent']
export const VarHighlighterProviderStyle: typeof import("../node_modules/@varlet/ui/es/highlighter-provider/style/index")['_HighlighterProviderStyleComponent']
export const VarHoverOverlay: typeof import("../node_modules/@varlet/ui/es/hover-overlay/index")['_HoverOverlayComponent']
export const VarHoverOverlayStyle: typeof import("../node_modules/@varlet/ui/es/hover-overlay/style/index")['_HoverOverlayStyleComponent']
export const VarHover: typeof import("../node_modules/@varlet/ui/es/hover/index")['_HoverComponent']
export const VarHoverStyle: typeof import("../node_modules/@varlet/ui/es/hover/style/index")['_HoverStyleComponent']
export const VarIcon: typeof import("../node_modules/@varlet/ui/es/icon/index")['_IconComponent']
export const VarIconStyle: typeof import("../node_modules/@varlet/ui/es/icon/style/index")['_IconStyleComponent']
export const VarImagePreview: typeof import("../node_modules/@varlet/ui/es/image-preview/index")['_ImagePreviewComponent']
export const VarImagePreviewStyle: typeof import("../node_modules/@varlet/ui/es/image-preview/style/index")['_ImagePreviewStyleComponent']
export const VarImage: typeof import("../node_modules/@varlet/ui/es/image/index")['_ImageComponent']
export const VarImageStyle: typeof import("../node_modules/@varlet/ui/es/image/style/index")['_ImageStyleComponent']
export const VarIndexAnchor: typeof import("../node_modules/@varlet/ui/es/index-anchor/index")['_IndexAnchorComponent']
export const VarIndexAnchorStyle: typeof import("../node_modules/@varlet/ui/es/index-anchor/style/index")['_IndexAnchorStyleComponent']
export const VarIndexBar: typeof import("../node_modules/@varlet/ui/es/index-bar/index")['_IndexBarComponent']
export const VarIndexBarStyle: typeof import("../node_modules/@varlet/ui/es/index-bar/style/index")['_IndexBarStyleComponent']
export const VarIndexBundle: typeof import("../node_modules/@varlet/ui/es/index.bundle")['_IndexBundleComponent']
export const Var: typeof import("../node_modules/@varlet/ui/es/index")['_Component']
export const VarInput: typeof import("../node_modules/@varlet/ui/es/input/index")['_InputComponent']
export const VarInputStyle: typeof import("../node_modules/@varlet/ui/es/input/style/index")['_InputStyleComponent']
export const VarLazy: typeof import("../node_modules/@varlet/ui/es/lazy/index")['_LazyComponent']
export const VarLazyStyle: typeof import("../node_modules/@varlet/ui/es/lazy/style/index")['_LazyStyleComponent']
export const VarLink: typeof import("../node_modules/@varlet/ui/es/link/index")['_LinkComponent']
export const VarLinkStyle: typeof import("../node_modules/@varlet/ui/es/link/style/index")['_LinkStyleComponent']
export const VarList: typeof import("../node_modules/@varlet/ui/es/list/index")['_ListComponent']
export const VarListStyle: typeof import("../node_modules/@varlet/ui/es/list/style/index")['_ListStyleComponent']
export const VarLoadingBar: typeof import("../node_modules/@varlet/ui/es/loading-bar/index")['_LoadingBarComponent']
export const VarLoadingBarStyle: typeof import("../node_modules/@varlet/ui/es/loading-bar/style/index")['_LoadingBarStyleComponent']
export const VarLoading: typeof import("../node_modules/@varlet/ui/es/loading/index")['_LoadingComponent']
export const VarLoadingStyle: typeof import("../node_modules/@varlet/ui/es/loading/style/index")['_LoadingStyleComponent']
export const VarLocaleProvider: typeof import("../node_modules/@varlet/ui/es/locale-provider/index")['_LocaleProviderComponent']
export const VarLocaleProviderStyle: typeof import("../node_modules/@varlet/ui/es/locale-provider/style/index")['_LocaleProviderStyleComponent']
export const VarLocale: typeof import("../node_modules/@varlet/ui/es/locale/index")['_LocaleComponent']
export const VarLocaleStyle: typeof import("../node_modules/@varlet/ui/es/locale/style/index")['_LocaleStyleComponent']
export const VarMenuOption: typeof import("../node_modules/@varlet/ui/es/menu-option/index")['_MenuOptionComponent']
export const VarMenuOptionStyle: typeof import("../node_modules/@varlet/ui/es/menu-option/style/index")['_MenuOptionStyleComponent']
export const VarMenuSelect: typeof import("../node_modules/@varlet/ui/es/menu-select/index")['_MenuSelectComponent']
export const VarMenuSelectStyle: typeof import("../node_modules/@varlet/ui/es/menu-select/style/index")['_MenuSelectStyleComponent']
export const VarMenu: typeof import("../node_modules/@varlet/ui/es/menu/index")['_MenuComponent']
export const VarMenuStyle: typeof import("../node_modules/@varlet/ui/es/menu/style/index")['_MenuStyleComponent']
export const VarOption: typeof import("../node_modules/@varlet/ui/es/option/index")['_OptionComponent']
export const VarOptionStyle: typeof import("../node_modules/@varlet/ui/es/option/style/index")['_OptionStyleComponent']
export const VarOverlay: typeof import("../node_modules/@varlet/ui/es/overlay/index")['_OverlayComponent']
export const VarOverlayStyle: typeof import("../node_modules/@varlet/ui/es/overlay/style/index")['_OverlayStyleComponent']
export const VarPagination: typeof import("../node_modules/@varlet/ui/es/pagination/index")['_PaginationComponent']
export const VarPaginationStyle: typeof import("../node_modules/@varlet/ui/es/pagination/style/index")['_PaginationStyleComponent']
export const VarPaper: typeof import("../node_modules/@varlet/ui/es/paper/index")['_PaperComponent']
export const VarPaperStyle: typeof import("../node_modules/@varlet/ui/es/paper/style/index")['_PaperStyleComponent']
export const VarPicker: typeof import("../node_modules/@varlet/ui/es/picker/index")['_PickerComponent']
export const VarPickerStyle: typeof import("../node_modules/@varlet/ui/es/picker/style/index")['_PickerStyleComponent']
export const VarPopup: typeof import("../node_modules/@varlet/ui/es/popup/index")['_PopupComponent']
export const VarPopupStyle: typeof import("../node_modules/@varlet/ui/es/popup/style/index")['_PopupStyleComponent']
export const VarProgress: typeof import("../node_modules/@varlet/ui/es/progress/index")['_ProgressComponent']
export const VarProgressStyle: typeof import("../node_modules/@varlet/ui/es/progress/style/index")['_ProgressStyleComponent']
export const VarPullRefresh: typeof import("../node_modules/@varlet/ui/es/pull-refresh/index")['_PullRefreshComponent']
export const VarPullRefreshStyle: typeof import("../node_modules/@varlet/ui/es/pull-refresh/style/index")['_PullRefreshStyleComponent']
export const VarRadioGroup: typeof import("../node_modules/@varlet/ui/es/radio-group/index")['_RadioGroupComponent']
export const VarRadioGroupStyle: typeof import("../node_modules/@varlet/ui/es/radio-group/style/index")['_RadioGroupStyleComponent']
export const VarRadio: typeof import("../node_modules/@varlet/ui/es/radio/index")['_RadioComponent']
export const VarRadioStyle: typeof import("../node_modules/@varlet/ui/es/radio/style/index")['_RadioStyleComponent']
export const VarRate: typeof import("../node_modules/@varlet/ui/es/rate/index")['_RateComponent']
export const VarRateStyle: typeof import("../node_modules/@varlet/ui/es/rate/style/index")['_RateStyleComponent']
export const VarResult: typeof import("../node_modules/@varlet/ui/es/result/index")['_ResultComponent']
export const VarResultStyle: typeof import("../node_modules/@varlet/ui/es/result/style/index")['_ResultStyleComponent']
export const VarRipple: typeof import("../node_modules/@varlet/ui/es/ripple/index")['_RippleComponent']
export const VarRippleStyle: typeof import("../node_modules/@varlet/ui/es/ripple/style/index")['_RippleStyleComponent']
export const VarRow: typeof import("../node_modules/@varlet/ui/es/row/index")['_RowComponent']
export const VarRowStyle: typeof import("../node_modules/@varlet/ui/es/row/style/index")['_RowStyleComponent']
export const VarSelect: typeof import("../node_modules/@varlet/ui/es/select/index")['_SelectComponent']
export const VarSelectStyle: typeof import("../node_modules/@varlet/ui/es/select/style/index")['_SelectStyleComponent']
export const VarSignature: typeof import("../node_modules/@varlet/ui/es/signature/index")['_SignatureComponent']
export const VarSignatureStyle: typeof import("../node_modules/@varlet/ui/es/signature/style/index")['_SignatureStyleComponent']
export const VarSkeleton: typeof import("../node_modules/@varlet/ui/es/skeleton/index")['_SkeletonComponent']
export const VarSkeletonStyle: typeof import("../node_modules/@varlet/ui/es/skeleton/style/index")['_SkeletonStyleComponent']
export const VarSlider: typeof import("../node_modules/@varlet/ui/es/slider/index")['_SliderComponent']
export const VarSliderStyle: typeof import("../node_modules/@varlet/ui/es/slider/style/index")['_SliderStyleComponent']
export const VarSnackbar: typeof import("../node_modules/@varlet/ui/es/snackbar/index")['_SnackbarComponent']
export const VarSnackbarStyle: typeof import("../node_modules/@varlet/ui/es/snackbar/style/index")['_SnackbarStyleComponent']
export const VarSpace: typeof import("../node_modules/@varlet/ui/es/space/index")['_SpaceComponent']
export const VarSpaceStyle: typeof import("../node_modules/@varlet/ui/es/space/style/index")['_SpaceStyleComponent']
export const VarStep: typeof import("../node_modules/@varlet/ui/es/step/index")['_StepComponent']
export const VarStepStyle: typeof import("../node_modules/@varlet/ui/es/step/style/index")['_StepStyleComponent']
export const VarSteps: typeof import("../node_modules/@varlet/ui/es/steps/index")['_StepsComponent']
export const VarStepsStyle: typeof import("../node_modules/@varlet/ui/es/steps/style/index")['_StepsStyleComponent']
export const VarSticky: typeof import("../node_modules/@varlet/ui/es/sticky/index")['_StickyComponent']
export const VarStickyStyle: typeof import("../node_modules/@varlet/ui/es/sticky/style/index")['_StickyStyleComponent']
export const VarStyleProvider: typeof import("../node_modules/@varlet/ui/es/style-provider/index")['_StyleProviderComponent']
export const VarStyleProviderStyle: typeof import("../node_modules/@varlet/ui/es/style-provider/style/index")['_StyleProviderStyleComponent']
export const VarStylesStyle: typeof import("../node_modules/@varlet/ui/es/styles/style/index")['_StylesStyleComponent']
export const VarSwipeItem: typeof import("../node_modules/@varlet/ui/es/swipe-item/index")['_SwipeItemComponent']
export const VarSwipeItemStyle: typeof import("../node_modules/@varlet/ui/es/swipe-item/style/index")['_SwipeItemStyleComponent']
export const VarSwipe: typeof import("../node_modules/@varlet/ui/es/swipe/index")['_SwipeComponent']
export const VarSwipeStyle: typeof import("../node_modules/@varlet/ui/es/swipe/style/index")['_SwipeStyleComponent']
export const VarSwitch: typeof import("../node_modules/@varlet/ui/es/switch/index")['_SwitchComponent']
export const VarSwitchStyle: typeof import("../node_modules/@varlet/ui/es/switch/style/index")['_SwitchStyleComponent']
export const VarTabItem: typeof import("../node_modules/@varlet/ui/es/tab-item/index")['_TabItemComponent']
export const VarTabItemStyle: typeof import("../node_modules/@varlet/ui/es/tab-item/style/index")['_TabItemStyleComponent']
export const VarTab: typeof import("../node_modules/@varlet/ui/es/tab/index")['_TabComponent']
export const VarTabStyle: typeof import("../node_modules/@varlet/ui/es/tab/style/index")['_TabStyleComponent']
export const VarTable: typeof import("../node_modules/@varlet/ui/es/table/index")['_TableComponent']
export const VarTableStyle: typeof import("../node_modules/@varlet/ui/es/table/style/index")['_TableStyleComponent']
export const VarTabsItems: typeof import("../node_modules/@varlet/ui/es/tabs-items/index")['_TabsItemsComponent']
export const VarTabsItemsStyle: typeof import("../node_modules/@varlet/ui/es/tabs-items/style/index")['_TabsItemsStyleComponent']
export const VarTabs: typeof import("../node_modules/@varlet/ui/es/tabs/index")['_TabsComponent']
export const VarTabsStyle: typeof import("../node_modules/@varlet/ui/es/tabs/style/index")['_TabsStyleComponent']
export const VarThemesDark: typeof import("../node_modules/@varlet/ui/es/themes/dark/index")['_ThemesDarkComponent']
export const VarThemes: typeof import("../node_modules/@varlet/ui/es/themes/index")['_ThemesComponent']
export const VarThemesMd3Dark: typeof import("../node_modules/@varlet/ui/es/themes/md3-dark/index")['_ThemesMd3DarkComponent']
export const VarThemesMd3Light: typeof import("../node_modules/@varlet/ui/es/themes/md3-light/index")['_ThemesMd3LightComponent']
export const VarThemesStyle: typeof import("../node_modules/@varlet/ui/es/themes/style/index")['_ThemesStyleComponent']
export const VarTimePicker: typeof import("../node_modules/@varlet/ui/es/time-picker/index")['_TimePickerComponent']
export const VarTimePickerStyle: typeof import("../node_modules/@varlet/ui/es/time-picker/style/index")['_TimePickerStyleComponent']
export const VarTooltip: typeof import("../node_modules/@varlet/ui/es/tooltip/index")['_TooltipComponent']
export const VarTooltipStyle: typeof import("../node_modules/@varlet/ui/es/tooltip/style/index")['_TooltipStyleComponent']
export const VarUploader: typeof import("../node_modules/@varlet/ui/es/uploader/index")['_UploaderComponent']
export const VarUploaderStyle: typeof import("../node_modules/@varlet/ui/es/uploader/style/index")['_UploaderStyleComponent']
export const VarUtilsStyle: typeof import("../node_modules/@varlet/ui/es/utils/style/index")['_UtilsStyleComponent']
export const VarWatermark: typeof import("../node_modules/@varlet/ui/es/watermark/index")['_WatermarkComponent']
export const VarWatermarkStyle: typeof import("../node_modules/@varlet/ui/es/watermark/style/index")['_WatermarkStyleComponent']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtTime: typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const VitePwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaManifest: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']
export const NuxtPwaAssets: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']
export const PwaAppleImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']
export const PwaAppleSplashScreenImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']
export const PwaFaviconImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']
export const PwaMaskableImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']
export const PwaTransparentImage: typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyVarActionSheet: LazyComponent<typeof import("../node_modules/@varlet/ui/es/action-sheet/index")['_ActionSheetComponent']>
export const LazyVarActionSheetStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/action-sheet/style/index")['_ActionSheetStyleComponent']>
export const LazyVarAlert: LazyComponent<typeof import("../node_modules/@varlet/ui/es/alert/index")['_AlertComponent']>
export const LazyVarAlertStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/alert/style/index")['_AlertStyleComponent']>
export const LazyVarAppBar: LazyComponent<typeof import("../node_modules/@varlet/ui/es/app-bar/index")['_AppBarComponent']>
export const LazyVarAppBarStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/app-bar/style/index")['_AppBarStyleComponent']>
export const LazyVarAutoComplete: LazyComponent<typeof import("../node_modules/@varlet/ui/es/auto-complete/index")['_AutoCompleteComponent']>
export const LazyVarAutoCompleteStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/auto-complete/style/index")['_AutoCompleteStyleComponent']>
export const LazyVarAvatarGroup: LazyComponent<typeof import("../node_modules/@varlet/ui/es/avatar-group/index")['_AvatarGroupComponent']>
export const LazyVarAvatarGroupStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/avatar-group/style/index")['_AvatarGroupStyleComponent']>
export const LazyVarAvatar: LazyComponent<typeof import("../node_modules/@varlet/ui/es/avatar/index")['_AvatarComponent']>
export const LazyVarAvatarStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/avatar/style/index")['_AvatarStyleComponent']>
export const LazyVarBackTop: LazyComponent<typeof import("../node_modules/@varlet/ui/es/back-top/index")['_BackTopComponent']>
export const LazyVarBackTopStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/back-top/style/index")['_BackTopStyleComponent']>
export const LazyVarBadge: LazyComponent<typeof import("../node_modules/@varlet/ui/es/badge/index")['_BadgeComponent']>
export const LazyVarBadgeStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/badge/style/index")['_BadgeStyleComponent']>
export const LazyVarBottomNavigationItem: LazyComponent<typeof import("../node_modules/@varlet/ui/es/bottom-navigation-item/index")['_BottomNavigationItemComponent']>
export const LazyVarBottomNavigationItemStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/bottom-navigation-item/style/index")['_BottomNavigationItemStyleComponent']>
export const LazyVarBottomNavigation: LazyComponent<typeof import("../node_modules/@varlet/ui/es/bottom-navigation/index")['_BottomNavigationComponent']>
export const LazyVarBottomNavigationStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/bottom-navigation/style/index")['_BottomNavigationStyleComponent']>
export const LazyVarBreadcrumb: LazyComponent<typeof import("../node_modules/@varlet/ui/es/breadcrumb/index")['_BreadcrumbComponent']>
export const LazyVarBreadcrumbStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/breadcrumb/style/index")['_BreadcrumbStyleComponent']>
export const LazyVarBreadcrumbs: LazyComponent<typeof import("../node_modules/@varlet/ui/es/breadcrumbs/index")['_BreadcrumbsComponent']>
export const LazyVarBreadcrumbsStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/breadcrumbs/style/index")['_BreadcrumbsStyleComponent']>
export const LazyVarButtonGroup: LazyComponent<typeof import("../node_modules/@varlet/ui/es/button-group/index")['_ButtonGroupComponent']>
export const LazyVarButtonGroupStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/button-group/style/index")['_ButtonGroupStyleComponent']>
export const LazyVarButton: LazyComponent<typeof import("../node_modules/@varlet/ui/es/button/index")['_ButtonComponent']>
export const LazyVarButtonStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/button/style/index")['_ButtonStyleComponent']>
export const LazyVarCard: LazyComponent<typeof import("../node_modules/@varlet/ui/es/card/index")['_CardComponent']>
export const LazyVarCardStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/card/style/index")['_CardStyleComponent']>
export const LazyVarCell: LazyComponent<typeof import("../node_modules/@varlet/ui/es/cell/index")['_CellComponent']>
export const LazyVarCellStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/cell/style/index")['_CellStyleComponent']>
export const LazyVarCheckboxGroup: LazyComponent<typeof import("../node_modules/@varlet/ui/es/checkbox-group/index")['_CheckboxGroupComponent']>
export const LazyVarCheckboxGroupStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/checkbox-group/style/index")['_CheckboxGroupStyleComponent']>
export const LazyVarCheckbox: LazyComponent<typeof import("../node_modules/@varlet/ui/es/checkbox/index")['_CheckboxComponent']>
export const LazyVarCheckboxStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/checkbox/style/index")['_CheckboxStyleComponent']>
export const LazyVarChip: LazyComponent<typeof import("../node_modules/@varlet/ui/es/chip/index")['_ChipComponent']>
export const LazyVarChipStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/chip/style/index")['_ChipStyleComponent']>
export const LazyVarCode: LazyComponent<typeof import("../node_modules/@varlet/ui/es/code/index")['_CodeComponent']>
export const LazyVarCodeStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/code/style/index")['_CodeStyleComponent']>
export const LazyVarCol: LazyComponent<typeof import("../node_modules/@varlet/ui/es/col/index")['_ColComponent']>
export const LazyVarColStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/col/style/index")['_ColStyleComponent']>
export const LazyVarCollapseItem: LazyComponent<typeof import("../node_modules/@varlet/ui/es/collapse-item/index")['_CollapseItemComponent']>
export const LazyVarCollapseItemStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/collapse-item/style/index")['_CollapseItemStyleComponent']>
export const LazyVarCollapseTransition: LazyComponent<typeof import("../node_modules/@varlet/ui/es/collapse-transition/index")['_CollapseTransitionComponent']>
export const LazyVarCollapseTransitionStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/collapse-transition/style/index")['_CollapseTransitionStyleComponent']>
export const LazyVarCollapse: LazyComponent<typeof import("../node_modules/@varlet/ui/es/collapse/index")['_CollapseComponent']>
export const LazyVarCollapseStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/collapse/style/index")['_CollapseStyleComponent']>
export const LazyVarContext: LazyComponent<typeof import("../node_modules/@varlet/ui/es/context/index")['_ContextComponent']>
export const LazyVarContextStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/context/style/index")['_ContextStyleComponent']>
export const LazyVarCountTo: LazyComponent<typeof import("../node_modules/@varlet/ui/es/count-to/index")['_CountToComponent']>
export const LazyVarCountToStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/count-to/style/index")['_CountToStyleComponent']>
export const LazyVarCountdown: LazyComponent<typeof import("../node_modules/@varlet/ui/es/countdown/index")['_CountdownComponent']>
export const LazyVarCountdownStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/countdown/style/index")['_CountdownStyleComponent']>
export const LazyVarCounter: LazyComponent<typeof import("../node_modules/@varlet/ui/es/counter/index")['_CounterComponent']>
export const LazyVarCounterStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/counter/style/index")['_CounterStyleComponent']>
export const LazyVarDatePicker: LazyComponent<typeof import("../node_modules/@varlet/ui/es/date-picker/index")['_DatePickerComponent']>
export const LazyVarDatePickerStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/date-picker/style/index")['_DatePickerStyleComponent']>
export const LazyVarDialog: LazyComponent<typeof import("../node_modules/@varlet/ui/es/dialog/index")['_DialogComponent']>
export const LazyVarDialogStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/dialog/style/index")['_DialogStyleComponent']>
export const LazyVarDivider: LazyComponent<typeof import("../node_modules/@varlet/ui/es/divider/index")['_DividerComponent']>
export const LazyVarDividerStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/divider/style/index")['_DividerStyleComponent']>
export const LazyVarDrag: LazyComponent<typeof import("../node_modules/@varlet/ui/es/drag/index")['_DragComponent']>
export const LazyVarDragStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/drag/style/index")['_DragStyleComponent']>
export const LazyVarEllipsis: LazyComponent<typeof import("../node_modules/@varlet/ui/es/ellipsis/index")['_EllipsisComponent']>
export const LazyVarEllipsisStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/ellipsis/style/index")['_EllipsisStyleComponent']>
export const LazyVarFab: LazyComponent<typeof import("../node_modules/@varlet/ui/es/fab/index")['_FabComponent']>
export const LazyVarFabStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/fab/style/index")['_FabStyleComponent']>
export const LazyVarFieldDecorator: LazyComponent<typeof import("../node_modules/@varlet/ui/es/field-decorator/index")['_FieldDecoratorComponent']>
export const LazyVarFieldDecoratorStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/field-decorator/style/index")['_FieldDecoratorStyleComponent']>
export const LazyVarFloatingPanel: LazyComponent<typeof import("../node_modules/@varlet/ui/es/floating-panel/index")['_FloatingPanelComponent']>
export const LazyVarFloatingPanelStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/floating-panel/style/index")['_FloatingPanelStyleComponent']>
export const LazyVarFormDetails: LazyComponent<typeof import("../node_modules/@varlet/ui/es/form-details/index")['_FormDetailsComponent']>
export const LazyVarFormDetailsStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/form-details/style/index")['_FormDetailsStyleComponent']>
export const LazyVarForm: LazyComponent<typeof import("../node_modules/@varlet/ui/es/form/index")['_FormComponent']>
export const LazyVarFormStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/form/style/index")['_FormStyleComponent']>
export const LazyVarHighlighterProvider: LazyComponent<typeof import("../node_modules/@varlet/ui/es/highlighter-provider/index")['_HighlighterProviderComponent']>
export const LazyVarHighlighterProviderStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/highlighter-provider/style/index")['_HighlighterProviderStyleComponent']>
export const LazyVarHoverOverlay: LazyComponent<typeof import("../node_modules/@varlet/ui/es/hover-overlay/index")['_HoverOverlayComponent']>
export const LazyVarHoverOverlayStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/hover-overlay/style/index")['_HoverOverlayStyleComponent']>
export const LazyVarHover: LazyComponent<typeof import("../node_modules/@varlet/ui/es/hover/index")['_HoverComponent']>
export const LazyVarHoverStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/hover/style/index")['_HoverStyleComponent']>
export const LazyVarIcon: LazyComponent<typeof import("../node_modules/@varlet/ui/es/icon/index")['_IconComponent']>
export const LazyVarIconStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/icon/style/index")['_IconStyleComponent']>
export const LazyVarImagePreview: LazyComponent<typeof import("../node_modules/@varlet/ui/es/image-preview/index")['_ImagePreviewComponent']>
export const LazyVarImagePreviewStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/image-preview/style/index")['_ImagePreviewStyleComponent']>
export const LazyVarImage: LazyComponent<typeof import("../node_modules/@varlet/ui/es/image/index")['_ImageComponent']>
export const LazyVarImageStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/image/style/index")['_ImageStyleComponent']>
export const LazyVarIndexAnchor: LazyComponent<typeof import("../node_modules/@varlet/ui/es/index-anchor/index")['_IndexAnchorComponent']>
export const LazyVarIndexAnchorStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/index-anchor/style/index")['_IndexAnchorStyleComponent']>
export const LazyVarIndexBar: LazyComponent<typeof import("../node_modules/@varlet/ui/es/index-bar/index")['_IndexBarComponent']>
export const LazyVarIndexBarStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/index-bar/style/index")['_IndexBarStyleComponent']>
export const LazyVarIndexBundle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/index.bundle")['_IndexBundleComponent']>
export const LazyVar: LazyComponent<typeof import("../node_modules/@varlet/ui/es/index")['_Component']>
export const LazyVarInput: LazyComponent<typeof import("../node_modules/@varlet/ui/es/input/index")['_InputComponent']>
export const LazyVarInputStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/input/style/index")['_InputStyleComponent']>
export const LazyVarLazy: LazyComponent<typeof import("../node_modules/@varlet/ui/es/lazy/index")['_LazyComponent']>
export const LazyVarLazyStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/lazy/style/index")['_LazyStyleComponent']>
export const LazyVarLink: LazyComponent<typeof import("../node_modules/@varlet/ui/es/link/index")['_LinkComponent']>
export const LazyVarLinkStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/link/style/index")['_LinkStyleComponent']>
export const LazyVarList: LazyComponent<typeof import("../node_modules/@varlet/ui/es/list/index")['_ListComponent']>
export const LazyVarListStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/list/style/index")['_ListStyleComponent']>
export const LazyVarLoadingBar: LazyComponent<typeof import("../node_modules/@varlet/ui/es/loading-bar/index")['_LoadingBarComponent']>
export const LazyVarLoadingBarStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/loading-bar/style/index")['_LoadingBarStyleComponent']>
export const LazyVarLoading: LazyComponent<typeof import("../node_modules/@varlet/ui/es/loading/index")['_LoadingComponent']>
export const LazyVarLoadingStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/loading/style/index")['_LoadingStyleComponent']>
export const LazyVarLocaleProvider: LazyComponent<typeof import("../node_modules/@varlet/ui/es/locale-provider/index")['_LocaleProviderComponent']>
export const LazyVarLocaleProviderStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/locale-provider/style/index")['_LocaleProviderStyleComponent']>
export const LazyVarLocale: LazyComponent<typeof import("../node_modules/@varlet/ui/es/locale/index")['_LocaleComponent']>
export const LazyVarLocaleStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/locale/style/index")['_LocaleStyleComponent']>
export const LazyVarMenuOption: LazyComponent<typeof import("../node_modules/@varlet/ui/es/menu-option/index")['_MenuOptionComponent']>
export const LazyVarMenuOptionStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/menu-option/style/index")['_MenuOptionStyleComponent']>
export const LazyVarMenuSelect: LazyComponent<typeof import("../node_modules/@varlet/ui/es/menu-select/index")['_MenuSelectComponent']>
export const LazyVarMenuSelectStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/menu-select/style/index")['_MenuSelectStyleComponent']>
export const LazyVarMenu: LazyComponent<typeof import("../node_modules/@varlet/ui/es/menu/index")['_MenuComponent']>
export const LazyVarMenuStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/menu/style/index")['_MenuStyleComponent']>
export const LazyVarOption: LazyComponent<typeof import("../node_modules/@varlet/ui/es/option/index")['_OptionComponent']>
export const LazyVarOptionStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/option/style/index")['_OptionStyleComponent']>
export const LazyVarOverlay: LazyComponent<typeof import("../node_modules/@varlet/ui/es/overlay/index")['_OverlayComponent']>
export const LazyVarOverlayStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/overlay/style/index")['_OverlayStyleComponent']>
export const LazyVarPagination: LazyComponent<typeof import("../node_modules/@varlet/ui/es/pagination/index")['_PaginationComponent']>
export const LazyVarPaginationStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/pagination/style/index")['_PaginationStyleComponent']>
export const LazyVarPaper: LazyComponent<typeof import("../node_modules/@varlet/ui/es/paper/index")['_PaperComponent']>
export const LazyVarPaperStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/paper/style/index")['_PaperStyleComponent']>
export const LazyVarPicker: LazyComponent<typeof import("../node_modules/@varlet/ui/es/picker/index")['_PickerComponent']>
export const LazyVarPickerStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/picker/style/index")['_PickerStyleComponent']>
export const LazyVarPopup: LazyComponent<typeof import("../node_modules/@varlet/ui/es/popup/index")['_PopupComponent']>
export const LazyVarPopupStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/popup/style/index")['_PopupStyleComponent']>
export const LazyVarProgress: LazyComponent<typeof import("../node_modules/@varlet/ui/es/progress/index")['_ProgressComponent']>
export const LazyVarProgressStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/progress/style/index")['_ProgressStyleComponent']>
export const LazyVarPullRefresh: LazyComponent<typeof import("../node_modules/@varlet/ui/es/pull-refresh/index")['_PullRefreshComponent']>
export const LazyVarPullRefreshStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/pull-refresh/style/index")['_PullRefreshStyleComponent']>
export const LazyVarRadioGroup: LazyComponent<typeof import("../node_modules/@varlet/ui/es/radio-group/index")['_RadioGroupComponent']>
export const LazyVarRadioGroupStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/radio-group/style/index")['_RadioGroupStyleComponent']>
export const LazyVarRadio: LazyComponent<typeof import("../node_modules/@varlet/ui/es/radio/index")['_RadioComponent']>
export const LazyVarRadioStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/radio/style/index")['_RadioStyleComponent']>
export const LazyVarRate: LazyComponent<typeof import("../node_modules/@varlet/ui/es/rate/index")['_RateComponent']>
export const LazyVarRateStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/rate/style/index")['_RateStyleComponent']>
export const LazyVarResult: LazyComponent<typeof import("../node_modules/@varlet/ui/es/result/index")['_ResultComponent']>
export const LazyVarResultStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/result/style/index")['_ResultStyleComponent']>
export const LazyVarRipple: LazyComponent<typeof import("../node_modules/@varlet/ui/es/ripple/index")['_RippleComponent']>
export const LazyVarRippleStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/ripple/style/index")['_RippleStyleComponent']>
export const LazyVarRow: LazyComponent<typeof import("../node_modules/@varlet/ui/es/row/index")['_RowComponent']>
export const LazyVarRowStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/row/style/index")['_RowStyleComponent']>
export const LazyVarSelect: LazyComponent<typeof import("../node_modules/@varlet/ui/es/select/index")['_SelectComponent']>
export const LazyVarSelectStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/select/style/index")['_SelectStyleComponent']>
export const LazyVarSignature: LazyComponent<typeof import("../node_modules/@varlet/ui/es/signature/index")['_SignatureComponent']>
export const LazyVarSignatureStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/signature/style/index")['_SignatureStyleComponent']>
export const LazyVarSkeleton: LazyComponent<typeof import("../node_modules/@varlet/ui/es/skeleton/index")['_SkeletonComponent']>
export const LazyVarSkeletonStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/skeleton/style/index")['_SkeletonStyleComponent']>
export const LazyVarSlider: LazyComponent<typeof import("../node_modules/@varlet/ui/es/slider/index")['_SliderComponent']>
export const LazyVarSliderStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/slider/style/index")['_SliderStyleComponent']>
export const LazyVarSnackbar: LazyComponent<typeof import("../node_modules/@varlet/ui/es/snackbar/index")['_SnackbarComponent']>
export const LazyVarSnackbarStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/snackbar/style/index")['_SnackbarStyleComponent']>
export const LazyVarSpace: LazyComponent<typeof import("../node_modules/@varlet/ui/es/space/index")['_SpaceComponent']>
export const LazyVarSpaceStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/space/style/index")['_SpaceStyleComponent']>
export const LazyVarStep: LazyComponent<typeof import("../node_modules/@varlet/ui/es/step/index")['_StepComponent']>
export const LazyVarStepStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/step/style/index")['_StepStyleComponent']>
export const LazyVarSteps: LazyComponent<typeof import("../node_modules/@varlet/ui/es/steps/index")['_StepsComponent']>
export const LazyVarStepsStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/steps/style/index")['_StepsStyleComponent']>
export const LazyVarSticky: LazyComponent<typeof import("../node_modules/@varlet/ui/es/sticky/index")['_StickyComponent']>
export const LazyVarStickyStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/sticky/style/index")['_StickyStyleComponent']>
export const LazyVarStyleProvider: LazyComponent<typeof import("../node_modules/@varlet/ui/es/style-provider/index")['_StyleProviderComponent']>
export const LazyVarStyleProviderStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/style-provider/style/index")['_StyleProviderStyleComponent']>
export const LazyVarStylesStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/styles/style/index")['_StylesStyleComponent']>
export const LazyVarSwipeItem: LazyComponent<typeof import("../node_modules/@varlet/ui/es/swipe-item/index")['_SwipeItemComponent']>
export const LazyVarSwipeItemStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/swipe-item/style/index")['_SwipeItemStyleComponent']>
export const LazyVarSwipe: LazyComponent<typeof import("../node_modules/@varlet/ui/es/swipe/index")['_SwipeComponent']>
export const LazyVarSwipeStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/swipe/style/index")['_SwipeStyleComponent']>
export const LazyVarSwitch: LazyComponent<typeof import("../node_modules/@varlet/ui/es/switch/index")['_SwitchComponent']>
export const LazyVarSwitchStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/switch/style/index")['_SwitchStyleComponent']>
export const LazyVarTabItem: LazyComponent<typeof import("../node_modules/@varlet/ui/es/tab-item/index")['_TabItemComponent']>
export const LazyVarTabItemStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/tab-item/style/index")['_TabItemStyleComponent']>
export const LazyVarTab: LazyComponent<typeof import("../node_modules/@varlet/ui/es/tab/index")['_TabComponent']>
export const LazyVarTabStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/tab/style/index")['_TabStyleComponent']>
export const LazyVarTable: LazyComponent<typeof import("../node_modules/@varlet/ui/es/table/index")['_TableComponent']>
export const LazyVarTableStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/table/style/index")['_TableStyleComponent']>
export const LazyVarTabsItems: LazyComponent<typeof import("../node_modules/@varlet/ui/es/tabs-items/index")['_TabsItemsComponent']>
export const LazyVarTabsItemsStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/tabs-items/style/index")['_TabsItemsStyleComponent']>
export const LazyVarTabs: LazyComponent<typeof import("../node_modules/@varlet/ui/es/tabs/index")['_TabsComponent']>
export const LazyVarTabsStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/tabs/style/index")['_TabsStyleComponent']>
export const LazyVarThemesDark: LazyComponent<typeof import("../node_modules/@varlet/ui/es/themes/dark/index")['_ThemesDarkComponent']>
export const LazyVarThemes: LazyComponent<typeof import("../node_modules/@varlet/ui/es/themes/index")['_ThemesComponent']>
export const LazyVarThemesMd3Dark: LazyComponent<typeof import("../node_modules/@varlet/ui/es/themes/md3-dark/index")['_ThemesMd3DarkComponent']>
export const LazyVarThemesMd3Light: LazyComponent<typeof import("../node_modules/@varlet/ui/es/themes/md3-light/index")['_ThemesMd3LightComponent']>
export const LazyVarThemesStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/themes/style/index")['_ThemesStyleComponent']>
export const LazyVarTimePicker: LazyComponent<typeof import("../node_modules/@varlet/ui/es/time-picker/index")['_TimePickerComponent']>
export const LazyVarTimePickerStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/time-picker/style/index")['_TimePickerStyleComponent']>
export const LazyVarTooltip: LazyComponent<typeof import("../node_modules/@varlet/ui/es/tooltip/index")['_TooltipComponent']>
export const LazyVarTooltipStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/tooltip/style/index")['_TooltipStyleComponent']>
export const LazyVarUploader: LazyComponent<typeof import("../node_modules/@varlet/ui/es/uploader/index")['_UploaderComponent']>
export const LazyVarUploaderStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/uploader/style/index")['_UploaderStyleComponent']>
export const LazyVarUtilsStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/utils/style/index")['_UtilsStyleComponent']>
export const LazyVarWatermark: LazyComponent<typeof import("../node_modules/@varlet/ui/es/watermark/index")['_WatermarkComponent']>
export const LazyVarWatermarkStyle: LazyComponent<typeof import("../node_modules/@varlet/ui/es/watermark/style/index")['_WatermarkStyleComponent']>
export const LazyNuxtWelcome: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']>
export const LazyNuxtLayout: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue")['default']>
export const LazyClientOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']>
export const LazyDevOnly: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']>
export const LazyServerPlaceholder: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyNuxtLink: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']>
export const LazyNuxtTime: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-time.vue")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']>
export const LazyNuxtImg: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']>
export const LazyNuxtPicture: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']>
export const LazyVitePwaManifest: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaManifest: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/VitePwaManifest")['default']>
export const LazyNuxtPwaAssets: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/NuxtPwaAssets")['default']>
export const LazyPwaAppleImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleImage.vue")['default']>
export const LazyPwaAppleSplashScreenImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaAppleSplashScreenImage.vue")['default']>
export const LazyPwaFaviconImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaFaviconImage.vue")['default']>
export const LazyPwaMaskableImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaMaskableImage.vue")['default']>
export const LazyPwaTransparentImage: LazyComponent<typeof import("../node_modules/@vite-pwa/nuxt/dist/runtime/components/PwaTransparentImage.vue")['default']>
export const LazyNuxtPage: LazyComponent<typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']>
export const LazyNoScript: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']>
export const LazyLink: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']>
export const LazyBase: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']>
export const LazyTitle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']>
export const LazyMeta: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']>
export const LazyStyle: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']>
export const LazyHead: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']>
export const LazyHtml: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']>
export const LazyBody: LazyComponent<typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']>
export const LazyNuxtIsland: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
